CREATE TABLE AUDIT_REPORTS
(
    audit_rep_id   INTEGER GENERATED BY DEFAULT AS IDENTITY,
    audit_schedule VARCHAR(255) DEFAULT 'scheduled',
    audit_type     VARCHAR(255) NOT NULL,
    subject        VARCHAR(255),
    start_date     DATE,
    end_date       DATE,
    location       VARCHAR(512),
    audited_by     VARCHAR(255),
    lead_auditor   INTEGER,
    auditor        VARCHAR(255),
    expert         VARCHAR(255),
    add_audit_team VARCHAR(255),
    auditee_name   VARCHAR(255),
    CONSTRAINT PK_AR PRIMARY KEY (audit_rep_id)
);

CREATE TABLE FINDINGS
(
    finding_id       INTEGER GENERATED BY DEFAULT AS IDENTITY,
    audit_rep_id     INTEGER NOT NULL,
    item             INTEGER,
    status           VARCHAR(128) DEFAULT 'Open',
    finding_desc     VARCHAR(1024),
    finding_level    VARCHAR(255),
    requirement_ext  VARCHAR(255),
    requirement_low  VARCHAR(255),
    due_date         DATE    NOT NULL,
    remaining_days   INTEGER computed by (due_date-CURRENT_DATE),
    root_cause_gen   VARCHAR(255),
    root_cause_desc  VARCHAR(1024),
    correct_act_plan VARCHAR(1024),
    corr_act_impl    VARCHAR(1024),
    prev_act_plan    VARCHAR(1024),
    prev_act_impl    VARCHAR(1024),
    closure_date     DATE,
    extension_date   DATE,
    extension_reason VARCHAR(255),
    remarks          VARCHAR(1024),
    resp             VARCHAR(255),
    co_resp          VARCHAR(255),
    CONSTRAINT CH_CLOSURE_DATE CHECK (closure_date<=due_date),
    CONSTRAINT CH_DUE_DATE CHECK (due_date > CURRENT_DATE),
    CONSTRAINT FK_AR FOREIGN KEY (AUDIT_REP_ID) REFERENCES AUDIT_REPORTS (AUDIT_REP_ID),
    CONSTRAINT PK_F PRIMARY KEY (FINDING_ID));
)